events {}

http {
    upstream article_api {
    server article-service-1:80;
    server article-service-2:80;
    server article-service-3:80;
}

    server {
        listen 80;
        location / {
            proxy_pass http://article_api;
        }
    }

}
